# version: '3'
# services:
#   zookeeper:
#     image: confluentinc/cp-zookeeper:latest
#     ports:
#       - '2181:2181'
#     networks:
#       - kafka-network
#   kafka:
#     image: confluentinc/cp-kafka:latest
#     ports:
#       - '9092:9092'
#     environment:
#       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#     depends_on:
#       - zookeeper
#     networks:
#       - kafka-network
# networks:
#   kafka-network:
#     driver: bridge
version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - '2181:2181'

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
